[package]
name = "generate_uuid_ulid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ulid = "0.6.0"
uuid = { version = "1.1.2", features = ["v4", "serde"] }
